# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/Dropbox/mark/analyses/networks/netpop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/Dropbox/mark/analyses/networks/netpop/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Dropbox/mark/analyses/networks/netpop/build/CMakeFiles /data/Dropbox/mark/analyses/networks/netpop/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Dropbox/mark/analyses/networks/netpop/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named net3

# Build rule for target.
net3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net3
.PHONY : net3

# fast build rule for target.
net3/fast:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/build
.PHONY : net3/fast

#=============================================================================
# Target rules for targets named net4

# Build rule for target.
net4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net4
.PHONY : net4

# fast build rule for target.
net4/fast:
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/build
.PHONY : net4/fast

#=============================================================================
# Target rules for targets named net_dend

# Build rule for target.
net_dend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_dend
.PHONY : net_dend

# fast build rule for target.
net_dend/fast:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/build
.PHONY : net_dend/fast

#=============================================================================
# Target rules for targets named net_latt

# Build rule for target.
net_latt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_latt
.PHONY : net_latt

# fast build rule for target.
net_latt/fast:
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/build
.PHONY : net_latt/fast

src/net3.o: src/net3.c++.o
.PHONY : src/net3.o

# target to build an object file
src/net3.c++.o:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/net3.c++.o
.PHONY : src/net3.c++.o

src/net3.i: src/net3.c++.i
.PHONY : src/net3.i

# target to preprocess a source file
src/net3.c++.i:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/net3.c++.i
.PHONY : src/net3.c++.i

src/net3.s: src/net3.c++.s
.PHONY : src/net3.s

# target to generate assembly for a file
src/net3.c++.s:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/net3.c++.s
.PHONY : src/net3.c++.s

src/net4.o: src/net4.c++.o
.PHONY : src/net4.o

# target to build an object file
src/net4.c++.o:
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/net4.c++.o
.PHONY : src/net4.c++.o

src/net4.i: src/net4.c++.i
.PHONY : src/net4.i

# target to preprocess a source file
src/net4.c++.i:
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/net4.c++.i
.PHONY : src/net4.c++.i

src/net4.s: src/net4.c++.s
.PHONY : src/net4.s

# target to generate assembly for a file
src/net4.c++.s:
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/net4.c++.s
.PHONY : src/net4.c++.s

src/network.o: src/network.c++.o
.PHONY : src/network.o

# target to build an object file
src/network.c++.o:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/network.c++.o
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/network.c++.o
.PHONY : src/network.c++.o

src/network.i: src/network.c++.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.c++.i:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/network.c++.i
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/network.c++.i
.PHONY : src/network.c++.i

src/network.s: src/network.c++.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.c++.s:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/network.c++.s
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/network.c++.s
.PHONY : src/network.c++.s

src/randnet_dendritic.o: src/randnet_dendritic.c++.o
.PHONY : src/randnet_dendritic.o

# target to build an object file
src/randnet_dendritic.c++.o:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/randnet_dendritic.c++.o
.PHONY : src/randnet_dendritic.c++.o

src/randnet_dendritic.i: src/randnet_dendritic.c++.i
.PHONY : src/randnet_dendritic.i

# target to preprocess a source file
src/randnet_dendritic.c++.i:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/randnet_dendritic.c++.i
.PHONY : src/randnet_dendritic.c++.i

src/randnet_dendritic.s: src/randnet_dendritic.c++.s
.PHONY : src/randnet_dendritic.s

# target to generate assembly for a file
src/randnet_dendritic.c++.s:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/randnet_dendritic.c++.s
.PHONY : src/randnet_dendritic.c++.s

src/randnet_lattice.o: src/randnet_lattice.c++.o
.PHONY : src/randnet_lattice.o

# target to build an object file
src/randnet_lattice.c++.o:
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/randnet_lattice.c++.o
.PHONY : src/randnet_lattice.c++.o

src/randnet_lattice.i: src/randnet_lattice.c++.i
.PHONY : src/randnet_lattice.i

# target to preprocess a source file
src/randnet_lattice.c++.i:
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/randnet_lattice.c++.i
.PHONY : src/randnet_lattice.c++.i

src/randnet_lattice.s: src/randnet_lattice.c++.s
.PHONY : src/randnet_lattice.s

# target to generate assembly for a file
src/randnet_lattice.c++.s:
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/randnet_lattice.c++.s
.PHONY : src/randnet_lattice.c++.s

src/utils.o: src/utils.c++.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c++.o:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/utils.c++.o
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/utils.c++.o
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/utils.c++.o
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/utils.c++.o
.PHONY : src/utils.c++.o

src/utils.i: src/utils.c++.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c++.i:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/utils.c++.i
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/utils.c++.i
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/utils.c++.i
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/utils.c++.i
.PHONY : src/utils.c++.i

src/utils.s: src/utils.c++.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c++.s:
	$(MAKE) -f CMakeFiles/net3.dir/build.make CMakeFiles/net3.dir/src/utils.c++.s
	$(MAKE) -f CMakeFiles/net4.dir/build.make CMakeFiles/net4.dir/src/utils.c++.s
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/utils.c++.s
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/utils.c++.s
.PHONY : src/utils.c++.s

src/utils_dendlatt.o: src/utils_dendlatt.c++.o
.PHONY : src/utils_dendlatt.o

# target to build an object file
src/utils_dendlatt.c++.o:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/utils_dendlatt.c++.o
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/utils_dendlatt.c++.o
.PHONY : src/utils_dendlatt.c++.o

src/utils_dendlatt.i: src/utils_dendlatt.c++.i
.PHONY : src/utils_dendlatt.i

# target to preprocess a source file
src/utils_dendlatt.c++.i:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/utils_dendlatt.c++.i
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/utils_dendlatt.c++.i
.PHONY : src/utils_dendlatt.c++.i

src/utils_dendlatt.s: src/utils_dendlatt.c++.s
.PHONY : src/utils_dendlatt.s

# target to generate assembly for a file
src/utils_dendlatt.c++.s:
	$(MAKE) -f CMakeFiles/net_dend.dir/build.make CMakeFiles/net_dend.dir/src/utils_dendlatt.c++.s
	$(MAKE) -f CMakeFiles/net_latt.dir/build.make CMakeFiles/net_latt.dir/src/utils_dendlatt.c++.s
.PHONY : src/utils_dendlatt.c++.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... net3"
	@echo "... net4"
	@echo "... net_dend"
	@echo "... net_latt"
	@echo "... rebuild_cache"
	@echo "... src/net3.o"
	@echo "... src/net3.i"
	@echo "... src/net3.s"
	@echo "... src/net4.o"
	@echo "... src/net4.i"
	@echo "... src/net4.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/randnet_dendritic.o"
	@echo "... src/randnet_dendritic.i"
	@echo "... src/randnet_dendritic.s"
	@echo "... src/randnet_lattice.o"
	@echo "... src/randnet_lattice.i"
	@echo "... src/randnet_lattice.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/utils_dendlatt.o"
	@echo "... src/utils_dendlatt.i"
	@echo "... src/utils_dendlatt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

